import { Property, FinancialAnalysis } from './types';

export const MOCK_PROPERTIES: Property[] = [
  {
    id: '1',
    address: '124 Maple Avenue',
    city: 'Austin',
    state: 'TX',
    zip: '78702',
    price: 450000,
    beds: 3,
    baths: 2,
    sqft: 1850,
    lotSize: 6500,
    yearBuilt: 1985,
    propertyType: 'Single Family',
    status: 'For Sale',
    imageUrl: 'https://picsum.photos/800/600?random=1',
    estimatedRent: 2800,
    description: 'Charming single-story home with updated kitchen and large backyard. Great rental potential in a rapidly appreciating neighborhood.',
    coordinates: { x: 20, y: 30 },
    features: ['Hardwood Floors', 'Updated Kitchen', 'Large Yard', 'Central AC'],
    lastSoldDate: '2018-05-15',
    lastSoldPrice: 320000,
  },
  {
    id: '2',
    address: '8802 Pine St',
    city: 'Austin',
    state: 'TX',
    zip: '78704',
    price: 625000,
    beds: 4,
    baths: 3,
    sqft: 2400,
    lotSize: 8000,
    yearBuilt: 2010,
    propertyType: 'Single Family',
    status: 'For Sale',
    imageUrl: 'https://picsum.photos/800/600?random=2',
    estimatedRent: 3500,
    description: 'Modern craftsman in the heart of the district. Walking distance to shops and cafes. High demand rental area.',
    coordinates: { x: 50, y: 45 },
    features: ['Modern Design', 'Walkable', 'Smart Home', '2 Car Garage'],
    lastSoldDate: '2021-02-10',
    lastSoldPrice: 550000,
  },
  {
    id: '3',
    address: '405 Oak Lane',
    city: 'Austin',
    state: 'TX',
    zip: '78701',
    price: 350000,
    beds: 2,
    baths: 1.5,
    sqft: 1100,
    lotSize: 0,
    yearBuilt: 1995,
    propertyType: 'Condo',
    status: 'Foreclosure',
    imageUrl: 'https://picsum.photos/800/600?random=3',
    estimatedRent: 2100,
    description: 'Investment opportunity! Foreclosure condo needing cosmetic updates. Below market value.',
    coordinates: { x: 75, y: 20 },
    features: ['Pool Access', 'Gym', 'Gated Community'],
    lastSoldDate: '2015-08-20',
    lastSoldPrice: 210000,
  },
  {
    id: '4',
    address: '2215 River Rd',
    city: 'Austin',
    state: 'TX',
    zip: '78703',
    price: 890000,
    beds: 5,
    baths: 4,
    sqft: 3200,
    lotSize: 10500,
    yearBuilt: 2022,
    propertyType: 'Multi Family',
    status: 'For Sale',
    imageUrl: 'https://picsum.photos/800/600?random=4',
    estimatedRent: 6000,
    description: 'Brand new duplex. Each side 2/2. Perfect for house hacking or pure cash flow play.',
    coordinates: { x: 35, y: 70 },
    features: ['New Construction', 'Duplex', 'High Rents', 'Quartz Countertops'],
    lastSoldDate: 'N/A',
    lastSoldPrice: 0,
  },
   {
    id: '5',
    address: '77 Sunset Blvd',
    city: 'Austin',
    state: 'TX',
    zip: '78705',
    price: 510000,
    beds: 3,
    baths: 2,
    sqft: 1600,
    lotSize: 5000,
    yearBuilt: 1970,
    propertyType: 'Single Family',
    status: 'Pending',
    imageUrl: 'https://picsum.photos/800/600?random=5',
    estimatedRent: 2600,
    description: 'Solid ranch style home near university. Consistent rental history.',
    coordinates: { x: 60, y: 80 },
    features: ['Near University', 'Stable Rents', 'Brick Exterior'],
    lastSoldDate: '2010-06-01',
    lastSoldPrice: 190000,
  }
];

export const INITIAL_FINANCIALS: FinancialAnalysis = {
  downPayment: 20,
  interestRate: 6.5,
  loanTerm: 30,
  closingCosts: 3,
  rehabCosts: 0,
  
  // Operating defaults
  propertyTaxRate: 1.8, // National avg proxy or TX specific (TX is high)
  insuranceRate: 0.6,
  hoa: 0,
  vacancyRate: 5,
  maintenanceRate: 5,
  managementRate: 8,

  // Results
  monthlyIncome: 0,
  monthlyExpenses: 0,
  cashFlow: 0,
  capRate: 0,
  cashOnCash: 0,
  totalInvestment: 0,
  breakdown: {
    mortgage: 0,
    taxes: 0,
    insurance: 0,
    hoa: 0,
    vacancy: 0,
    maintenance: 0,
    management: 0
  }
};